In [1]:
#예제 1

symbols = "$*&!@"
codes = []

for symbol in symbols:
  codes.append(ord(symbol))

print(codes)

[36, 42, 38, 33, 64]


In [2]:
#예제 2

symbols = "$*&!@"
codes = [ord(symbol) for symbol in symbols]

print(codes)

[36, 42, 38, 33, 64]


In [3]:
#예제 3

x = '"!~$$*&!@'
dummy = [ord(x) for x in x]

print(x)
print(dummy)

"!~$$*&!@
[34, 33, 126, 36, 36, 42, 38, 33, 64]


In [4]:
#예제 4

symbols = '"!~$$*&!@'
beyond_ascii = [ord(s) for s in symbols if ord(s) > 32]

print(beyond_ascii)

[34, 33, 126, 36, 36, 42, 38, 33, 64]


In [5]:
#예제 5

symbols = '"!~$$*&!@'
beyond_ascii = list(filter(lambda c: c > 64, map(ord, symbols)))

print(beyond_ascii, '\n')

print(f"Map function:\n>>> {map(ord, symbols)}")
print(f"List function:\n>>> {list(map(ord, symbols))}")

[126] 

Map function:
>>> <map object at 0x7de9ab1c1bd0>
List function:
>>> [34, 33, 126, 36, 36, 42, 38, 33, 64]


In [6]:
#예제 6

colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirts = [(color, size) for color in colors for size in sizes]

print(tshirts)

for color in colors:
  for size in sizes:
    print((color, size))

[('black', 'S'), ('black', 'M'), ('black', 'L'), ('white', 'S'), ('white', 'M'), ('white', 'L')]
('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


In [8]:
#예제 7

symbols = "!#^&&#"
ord_s = tuple(ord(s) for s in symbols if ord(s))

print(ord_s)

(33, 35, 94, 38, 38, 35)


In [9]:
#예제 8

colors = ['black', 'white']
sizes = ['S', 'M', 'L']

for tshirt in ('{} {}'.format(c,s) for s in sizes for c in colors):
  print(tshirt)

black S
white S
black M
white M
black L
white L


In [11]:
#예제 9

lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)
traveler_ids = [('USA', '31195855'), ('BRA', 'CE342567'), ('ESP', 'XDA205856')]

for passport in sorted(traveler_ids):
  print('%s/%s' % passport)
  print('{} {}'.format(passport[0], passport[1]))
  print(f'{passport[0]} {passport[1]}')

BRA/CE342567
BRA CE342567
BRA CE342567
ESP/XDA205856
ESP XDA205856
ESP XDA205856
USA/31195855
USA 31195855
USA 31195855


In [12]:
#예제 10

for country, _ in traveler_ids:
  print(country)

USA
BRA
ESP


In [13]:
#예제 11

lax_coordinates = (33.9425, -118.408056)
latitude, longitude = lax_coordinates
print(latitude)
print(longitude)

33.9425
-118.408056


In [14]:
#예제 12

a, b = 10, 20
a, b = b, a
print(a, b)

20 10


In [15]:
#예제 13

divmod(20, 8)

t = (20, 8)
divmod(*t)

quotient, remainder = divmod(*t)
quotient, remainder

(2, 4)

In [16]:
#예제 14

import os
_, filename = os.path.split('/home/luciano/.ssh/idrsa.pub')
filename

'idrsa.pub'

In [17]:
#예제 15

a, b, *rest = range(5)
print(a, b, rest)

a, b, *rest = range(3)
print(a, b, rest)

a, b, *rest = range(2)
print(a, b, rest)

0 1 [2, 3, 4]
0 1 [2]
0 1 []


In [18]:
#예제 16

a, *body, c, d = range(5)
print(a, body, c, d)

*head, b, c, d = range(5)
print(head, b, c, d)

0 [1, 2] 3 4
[0, 1] 2 3 4


In [20]:
#예제 17

metro_areas = [
    ('Tokyo', 'JP', 36.933, (35, 139)),
    ('Delhi NCR', 'IN', 21, (28, 77)),
    ('Mexico City', 'MX', 20, (19, -99)),
    ('New York-Newark', 'US', 20, (40, -74)),
    ('Sao Paulo', 'BR', 19, (-23, -46))
]

print('{:15} | {:^9} | {:^9}'.format('', 'lat.', 'long.'))
fmt = '{:15} | {:9.4f} | {:9.4f}'

for name, cc, pop, (lat, longi) in metro_areas:
  if longi <= 0:
    print(fmt.format(name, lat, longi))

                |   lat.    |   long.  
Mexico City     |   19.0000 |  -99.0000
New York-Newark |   40.0000 |  -74.0000
Sao Paulo       |  -23.0000 |  -46.0000


In [21]:
#예제 18

from collections import namedtuple
City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689, 139.691))
print(tokyo)

City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689, 139.691))


In [24]:
#예제 19

City._fields

LatLong = namedtuple('LatLong', 'lat long')
delhi_data = ('Delhi NCR', 'IN', 21.935, LatLong(28.613, 77.208))
delhi = City._make(delhi_data)
delhi._asdict()

for key, value in delhi._asdict().items():
  print(key + ':', value)

name: Delhi NCR
country: IN
population: 21.935
coordinates: LatLong(lat=28.613, long=77.208)


In [25]:
#예제 20

l = [10, 20, 30, 40, 50, 60]
print(l[:2])
print(l[2:])
print(l[:3])
print(l[3:])

[10, 20]
[30, 40, 50, 60]
[10, 20, 30]
[40, 50, 60]


In [26]:
#예제 21

invoice = """
0.....6..................25........33......40.......
1909  Pimoroni              $17.50    3     $52.50
1489  6mm Tactile           $4.95     2     $9.90
"""

SKU = slice(0, 6)
DESCRIPTION = slice(6, 25)
UNIT_PRICE = slice(25, 33)
QUANTITY = slice(33, 40)
ITEM_TOTAL = slice(40, None)

line_items = invoice.split('\n')[2:]

for item in line_items:
  print(item[UNIT_PRICE], item[DESCRIPTION])

   $17.5 Pimoroni           
   $4.95 6mm Tactile        
 


In [27]:
#예제 22

l = list(range(10))
print(l)

l[2:5] = [20, 30]
print(l)

del l[5:7]
print(l)

l[3::2] = [11, 22]
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 20, 30, 5, 6, 7, 8, 9]
[0, 1, 20, 30, 5, 8, 9]
[0, 1, 20, 11, 5, 22, 9]


In [28]:
#예제 23

l[2:5] = 100

TypeError: must assign iterable to extended slice

In [30]:
#예제 24

l[2:5] = [100]
l

[0, 1, 100, 22, 9]

In [33]:
#예제 25

l = [1, 2, 3]
print(l * 5)

print(5 * 'abcd')

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
abcdabcdabcdabcdabcd


In [34]:
#예제 26

board = [['_'] * 3 for i in range(3)]
print(board)

board[1][2] = 'X'
print(board)

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]


In [36]:
#예제 27

weird_board = [['_'] * 3] * 3
print(weird_board)

weird_board[1][2] = 'O'
print(weird_board)

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', '_', 'O'], ['_', '_', 'O'], ['_', '_', 'O']]


In [37]:
#예제 28

row = ['_'] * 3
board = []
for i in range(3):
  board.append(row)
print(board)

board[1][2] = 'X'

print(board)

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', '_', 'X'], ['_', '_', 'X'], ['_', '_', 'X']]


In [38]:
#예제 29

board = []
for i in range(3):
  row = ['_'] * 3
  board.append(row)
print(board)

board[2][0] = 'X'
print(board)

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', '_', '_'], ['_', '_', '_'], ['X', '_', '_']]


In [39]:
#예제 30

l = [1, 2, 3]
print(id(l))

l *= 2
print(l)

print(id(l))

138442271666752
[1, 2, 3, 1, 2, 3]
138442271666752


In [40]:
#예제 31

t = (1, 2, 3)
print(id(t))

t *= 2
print(t)

print(id(t))

138443038732544
(1, 2, 3, 1, 2, 3)
138442272804672


In [42]:
#예제 32

t = (1, 2, [30, 40])
print(t)

t[2] += [50, 60]

"""
a. t는 (1, 2, [30, 40, 50, 60])이 된다.
b. '튜플 객체는 항목 할당을 지원하지 않는다'는
    메시지와 함께 TypeError가 발생한다.
c. a와 b 둘 다 틀리다.
d. a와 b 둘 다 맞다.
"""

(1, 2, [30, 40])


TypeError: 'tuple' object does not support item assignment

In [43]:
#예제 33

print(t)

(1, 2, [30, 40, 50, 60])


In [44]:
#예제 34

fruits = ['grape', 'raspberry', 'apple', 'banana']
print(sorted(fruits))

print(fruits)

print(sorted(fruits, reverse=True))

print(sorted(fruits, key=len))

['apple', 'banana', 'grape', 'raspberry']
['grape', 'raspberry', 'apple', 'banana']
['raspberry', 'grape', 'banana', 'apple']
['grape', 'apple', 'banana', 'raspberry']


In [46]:
#예제 35

print(sorted(fruits, key=len, reverse=True))

print(fruits)

fruits.sort()
print(fruits)

['raspberry', 'banana', 'apple', 'grape']
['apple', 'banana', 'grape', 'raspberry']
['apple', 'banana', 'grape', 'raspberry']


In [47]:
#예제 36

from array import array
from random import random

floats = array('d', (random() for i in range(10**7)))
print(floats[-1])

0.6475095067813184


In [48]:
#예제 37

with open('floats.bin', 'wb') as f:
  floats.tofile(f)

floats2 = array('d')

with open('floats.bin', 'rb') as f:
  floats2.fromfile(f, 10**7)

print(floats2[-1])

floats == floats2

0.6475095067813184


True

In [49]:
#예제 38

import array
numbers = array.array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
print(len(memv))

print(memv[0])

memv_oct = memv.cast('B')
print(memv_oct.tolist())

memv_oct[5] = 4
print(numbers)

5
-2
[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]
array('h', [-2, -1, 1024, 1, 2])


In [50]:
#예제 38-1

data = bytearray(b'helloworld')
mv = memoryview(data)

print(mv[0])
mv[0] = 72

print(data)

104
bytearray(b'Helloworld')


In [51]:
#예제 39

import numpy
a = numpy.arange(12)
print(a)

print(type(a))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>


In [52]:
#예제 40

print(a.shape)

a.shape = 3, 4
print(a)

(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [53]:
#예제 41

print(a[2])

print(a[2, 1])

print(a[:, 1])

[ 8  9 10 11]
9
[1 5 9]


In [54]:
#예제 42

a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])